language: nix

os:
  - linux
  - osx

install:
  - nix-env -i clang mercurial ninja python3 ripgrep vim zsh

before_script:
  - rm -f ~/.zshrc
  - ./install.sh "${HOME}"

script:
  - make
  - make check
  - make format
  - git diff --exit-code
