language: nix

os:
  - linux
  - osx

script:
  - rm -f ~/.zshrc
  - ./install.sh "${HOME}"

  - ./install-packages
  - nix-env -i bazaar mercurial ninja

  - make
  - make check
  - make format
  - git diff --exit-code
