language: nix

os:
  - linux
  - osx

install:
  - nix-env -i clang ninja ripgrep vim zsh

before_script:
  - ./install.sh "${HOME}"

script:
  - make check-zsh
  - ./vim/test.sh
  - make
  - git diff --exit-code
