language: nix

os:
  - linux
  - osx

install:
  - ./install-packages
  - nix-env -i bazaar mercurial ninja

before_script:
  - rm -f ~/.zshrc
  - ./install.sh "${HOME}"

script:
  - make
  - make check
  - make format
  - git diff --exit-code
