language: minimal

os:
  - linux
  - osx

script:
  - set -e

  - wget --retry-connrefused --waitretry=1 -O nix-install https://nixos.org/releases/nix/nix-2.3.10/install
  - yes | sh nix-install
  - . ~/.nix-profile/etc/profile.d/nix.sh

  - nix-channel --remove nixpkgs
  - nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
  - nix-channel --update
  - nix-channel --list
  - nix-env --version

  - rm -f ~/.zshrc
  - ./install.sh "${HOME}"

  - ./install-packages
  - nix-env -i mercurial ninja
  - case "$(uname)" in Linux) sudo apt-get install bzr ;; Darwin) brew install bzr ;; esac

  - make
  - make check
  - make format
  - git diff --exit-code
